[build]
installCommand = 'pip install -r requirements.txt'

[start]
cmd = "PYTHONPATH=/app/backend uvicorn backend.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips='*'"

[variables]
PYTHONPATH = "/app/backend"
